### ISSUE TITLE
Columns with spaces

### ISSUE THREAD

**Issue by itsdeluxe** [implydata/plywood#89]
Any way to get the apply function to work with spaces in column names?

var context = {
  "dataset": dataset,
  "log_count": "Log Count"
}

.apply('Log Count', '$dataset.sum($log_count)')

Error: sum must have expression of type NUMBER (is STRING)
    at SumAction.Action._checkExpressionTypes (/root/druid/node_modules/plywood/build/plywood.js:7579:27)
    at new SumAction (/root/druid/node_modules/plywood/build/plywood.js:10306:18)
    at SumAction.Action._substituteHelper (/root/druid/node_modules/plywood/build/plywood.js:7750:20)
    at /root/druid/node_modules/plywood/build/plywood.js:7247:76
    at Array.map (native)
    at ChainExpression._substituteHelper (/root/druid/node_modules/plywood/build/plywood.js:7247:38)
    at ApplyAction.Action._substituteHelper (/root/druid/node_modules/plywood/build/plywood.js:7744:44)
    at /root/druid/node_modules/plywood/build/plywood.js:7247:76
    at Array.map (native)
    at ChainExpression._substituteHelper (/root/druid/node_modules/plywood/build/plywood.js:7247:38)

**Comment by itsdeluxe** [comment]
When I run plyql from the command line it allows me to add ticks and works fine.  i.e. `Log Count`

**Comment by vogievetsky** [comment]
In plywood if you had a space you could do: `.apply('Log Count', '$dataset.sum(${log count})')`
